[meta]
plugin_metadata_version = 0

[plugin]
name = "libbs"
shortname = "libbs"
version = "0.0.0"
description = ""
long_description = ""
platforms = ["windows", "linux", "macos"]
min_angr_version = "9.0.0.0"
author = "The BinSync Team"
entrypoints = ["__init__.py"]