from libbs.ui.version import ui_version

if ui_version == "PySide6":
    from PySide6.QtCore import (
        QDir, Qt, Signal, QAbstractTableModel, QModelIndex, QSortFilterProxyModel, QPersistentModelIndex,
        QEvent, QThread, Slot, QObject, QPropertyAnimation, QAbstractAnimation, QParallelAnimationGroup,
        QLineF, QTimer, QRect,
    )
    from PySide6.QtWidgets import (
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QDialog,
        QFileDialog,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QLabel,
        QLineEdit,
        QMenu,
        QMessageBox,
        QPushButton,
        QStatusBar,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QVBoxLayout,
        QWidget,
        QDialogButtonBox,
        QTableView,
        QFontDialog,
        QCheckBox,
        QMainWindow,
        QApplication,
        QFrame,
        QWidget,
        QSizePolicy,
        QScrollArea,
        QToolButton,
        QProgressBar,
        QGraphicsScene,
        QGraphicsView,
        QGraphicsEllipseItem,
        QGraphicsTextItem,
        QGraphicsLineItem,
        QGraphicsItem,
        QToolTip,
    )
    from PySide6.QtGui import (
        QFontDatabase,
        QColor,
        QKeyEvent,
        QFocusEvent,
        QIntValidator,
        QAction,
        QImage,
        QFontMetrics,
        QFont,
        QPainter,
        QBrush,
        QPen,
        QCursor,
    )
    from shiboken6 import wrapInstance
else:
    from PyQt5.QtCore import (
        QDir, Qt, QAbstractTableModel, QModelIndex, QSortFilterProxyModel, QPersistentModelIndex,
        QEvent, QThread, QObject, QPropertyAnimation, QAbstractAnimation, QParallelAnimationGroup,
        QLineF, QTimer, QRect,
    )
    from PyQt5.QtCore import pyqtSignal as Signal
    from PyQt5.QtCore import pyqtSlot as Slot
    from PyQt5.QtWidgets import (
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QDialog,
        QFileDialog,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QLabel,
        QLineEdit,
        QMenu,
        QMessageBox,
        QPushButton,
        QStatusBar,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QVBoxLayout,
        QWidget,
        QDialogButtonBox,
        QTableView,
        QAction,
        QFontDialog,
        QCheckBox,
        QMainWindow,
        QApplication,
        QFrame,
        QWidget,
        QSizePolicy,
        QScrollArea,
        QToolButton,
        QProgressBar,
        QGraphicsScene,
        QGraphicsView,
        QGraphicsEllipseItem,
        QGraphicsTextItem,
        QGraphicsLineItem,
        QGraphicsItem,
        QToolTip,
    )
    from PyQt5.QtGui import (
        QFontDatabase,
        QColor,
        QKeyEvent,
        QFocusEvent,
        QIntValidator,
        QImage,
        QFontMetrics,
        QFont,
        QPainter,
        QBrush,
        QPen,
        QCursor,
    )
    try:
        # new location for sip
        # https://www.riverbankcomputing.com/static/Docs/PyQt5/incompatibilities.html#pyqt-v5-11
        from PyQt5.sip import wrapinstance as wrapInstance
    except ImportError:
        from sip import wrapinstance as wrapInstance

