# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Artifact Tests

on:
  push:
    branches: [ main ]
    paths: ['libbs/artifacts/**']
  pull_request:
    branches: [ main ]
    paths: ['libbs/artifacts/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .

      - name: Pytest
        run: |
          pytest ./tests/test_artifacts.py
