[meta]
plugin_metadata_version = 0

[plugin]
name = "bs_change_watcher"
shortname = "bs_change_watcher"
version = "0.0.0"
description = ""
long_description = ""
platforms = ["windows", "linux", "macos"]
min_angr_version = "9.0.0.0"
author = "The BinSync Team"
entrypoints = ["bs_change_watcher_plugin.py"]